### ISSUE TITLE
I just downloaded you file and when I run I am getting following error

### ISSUE THREAD

**Issue by shreyash97** [bunnykek/jiosaavn-dl#1]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'ffmpeg'
  File "[/Users/vertigo/Desktop/jiosaavn-dl/jiosaavn.py]()", line 224, in <module>
    subprocess.Popen(["ffmpeg", "-y", "-i", song_json["image"].replace("150", "500"),

Downloading the cover...
Traceback (most recent call last):
  File "/Users/vertigo/Desktop/jiosaavn-dl/jiosaavn.py", line 224, in <module>
    subprocess.Popen(["ffmpeg", "-y", "-i", song_json["image"].replace("150", "500"),
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

It does pull the file info and crash after Downloading the cover... file

I am on M1 macbook pro with python3 
i downloaded the ffmpeg 4.4.1 binaries named for osx-64

Please advice next actions

**Comment by bunnykek** [comment]
Its a issue from your side.
The program is unable to find the ffmpeg binary.
https://www.youtube.com/watch?v=nmrjRqEIgGc
Follow this video, I dont have M1 Mac and its the only easy tutorial i found. 
Let me know if it worked for you.

**Comment by shreyash97** [comment]
Thank you for getting back. Do I have to install ffmpeg or just copy that binary file into that jiosaavn-dl directory? I will try to follow that youtube tutorial
________________________________

**Comment by bunnykek** [comment]
Delete the ffmpeg binary which you have already downloaded and then follow the video.
After then try using jiosaavn-dl

**Comment by shreyash97** [comment]
Thank You again. That did work for me after installing ffmpeg. Thanks again
________________________________

**Comment by bunnykek** [comment]
Good to hear that. Enjoy
