### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by chaitrakiran2010** [bunnykek/jiosaavn-dl#3]
It is not working any more.

**Comment by chaitrakiran2010** [comment]
here is the error

Traceback (most recent call last):
  File "G:\jiosaavn-dl\jiosaavn.py", line 148, in <module>
    album_id = get_id(response, "album_id")
  File "G:\jiosaavn-dl\jiosaavn.py", line 43, in get_id
    return(re.search(f'\"{identity}\":\".*?\"', response.text).group().replace(f'\"{identity}\":\"', "").replace("\"", ""))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by bunnykek** [comment]
Its working fine for me. Send the URL which you are using.

**Comment by chaitrakiran2010** [comment]
here is the URL

https://www.jiosaavn.com/album/deguladi-from-mancha/vH0N09XEL50_

**Comment by chaitrakiran2010** [comment]
It is not working for Pro only version Albums, songs.....

**Comment by chaitrakiran2010** [comment]
Here is the not working huge URL

https://www.jiosaavn.com/album/aarathi-belagire-vol-2/M5Unr5DKCF4_
https://www.jiosaavn.com/album/adbutha-ramayana-adharitha-pouranika-nataka---lava-kusha-vol-1/vuAe3PtdYVQ_
https://www.jiosaavn.com/album/adbutha-ramayana-adharitha-pouranika-nataka---lava-kusha-vol-2/edwDNRRiU9w_
https://www.jiosaavn.com/album/agra-pooje/ffZj9RZnHg4_
https://www.jiosaavn.com/album/akka-nagammana-pavada/AQ6cGSevkh8_
https://www.jiosaavn.com/album/ananda-nilaya-inspector-jayasimha/UMu-I8jNyOc_
https://www.jiosaavn.com/album/annadaani-bhairoova/gE-GNtpoFOs_
https://www.jiosaavn.com/album/anna-nodonu-baro-sharif-songs--vol-2/z8VRGxCeLEo_
https://www.jiosaavn.com/album/arathi-belagire-chamundige/qlzNjreedwc_
https://www.jiosaavn.com/album/ayyappa-top-10/m-svjorP5IE_
https://www.jiosaavn.com/album/baara-nanna-saradara/KMUOdxyFjGI_
https://www.jiosaavn.com/album/bale..cha..pakra-vol-2/UoNzxDLmF1E_
https://www.jiosaavn.com/album/bale..cha..parka-vol-1/ioWZrLQqIec_
https://www.jiosaavn.com/album/bandhu-balaga/lM24vcKs9DE_
https://www.jiosaavn.com/album/bandithamma-bandithamma-shukravaara/l,Z7WX0gz6w_
https://www.jiosaavn.com/album/banje-honnamma/QxPT-LPiq1M_
https://www.jiosaavn.com/album/bevinahatti-kalamma/zfXRTV4N3y0_
https://www.jiosaavn.com/album/bhaagyada-lakshmi-baarammaayagiri-nandini/r96xysqwM-A_
https://www.jiosaavn.com/album/bhagyada-lakshmi-baaramma/,bb9nhfaLJc_
https://www.jiosaavn.com/album/bhagyada-lakshmi-baaramma/i8wmaB1e5gs_
https://www.jiosaavn.com/album/bhagyada-lakshmi-baaramma/ZE9XzFWEQGQ_
https://www.jiosaavn.com/album/bhakthere-appe-bramari/rxW0J8H,59Q_
https://www.jiosaavn.com/album/bhakthida-abhisheka/ja8ggFofGos_
https://www.jiosaavn.com/album/bhakthida-pooje/1Ec0RNHwftg_
https://www.jiosaavn.com/album/bhakthi-sowrabha/hAm9WFm7N4w_
https://www.jiosaavn.com/album/bittu-hogabyada-gelathi-north-karnatka-folk-songs/lac4iv,Ap3k_
https://www.jiosaavn.com/album/carnatic-classical-vocal---o.s.thyagarajan/pB7Ss5KM9MY_
https://www.jiosaavn.com/album/chamachavathara/,ELT-seJBhA_
https://www.jiosaavn.com/album/chandrahasa/FxK0Flys2Ic_
https://www.jiosaavn.com/album/daasara-padagalu/5QIqkXnQuBY_
https://www.jiosaavn.com/album/daasavani-part.2/Q2kCi53NZCI_
https://www.jiosaavn.com/album/daasavani-part-1/bzKvhtz7X5A_
https://www.jiosaavn.com/album/daasavani-part-1/wvcIJuL0fiw_
https://www.jiosaavn.com/album/dagaar-rajakiya/g3j6smgc6KU_
https://www.jiosaavn.com/album/devi-sangama/qsszyWGhlh0_
https://www.jiosaavn.com/album/dharegilida-sri-mahalakshmi/vLzsYvX2ZAQ_
https://www.jiosaavn.com/album/dharmasthala-vaasa-shri-manjuntha/LnjzAlogKBk_
https://www.jiosaavn.com/album/enna-apsare/ukYkZyjx5lI_
https://www.jiosaavn.com/album/enna-love-story/1,jmT5NMMvs_
https://www.jiosaavn.com/album/eshwar-allah-neene-baaba/T-bVW8zqZ5Y_
https://www.jiosaavn.com/album/ethereal-duet-karnatic-classical-instrumental/fxNEXce4mRI_
https://www.jiosaavn.com/album/evergreen-melodies-bellur-sisters/,im,Ux,Usy8_
https://www.jiosaavn.com/album/force-2/DzPP2dB42vM_
https://www.jiosaavn.com/album/gaja-sowri-wratha/Bp29,3ZqQBw_
https://www.jiosaavn.com/album/gangya-mangya/VrlRAdqE,CM_
https://www.jiosaavn.com/album/garadi-mani-gadi/ygq9NPY5gR4_
https://www.jiosaavn.com/album/gejje-ghalirendo/WFD9P0niVIc_
https://www.jiosaavn.com/album/ghatothkach-master-of-magic/TfOT6jpe0tU_
https://www.jiosaavn.com/album/goravanahalli-sri-mahalakshmi-manas/vTHpWdDWmmQ_
https://www.jiosaavn.com/album/gulaganji/3yepm2o,Qqo_
https://www.jiosaavn.com/album/gunjumale-maadeva/4-xvpn1fAsw_
https://www.jiosaavn.com/album/guruvina-mathu-dollina-padagalu/wSUOyv4OruM_
https://www.jiosaavn.com/album/haridasara---sri-raghavendra-namawali/IIjNVR,wrYE_
https://www.jiosaavn.com/album/haridasaru-kanda-sri-vinayaka/Pt1Qj2SvMVM_
https://www.jiosaavn.com/album/hari-kunida-dasara-padagalu/QYiLZbbRp3w_
https://www.jiosaavn.com/album/hemramba-ganapa/VioldPrdRBo_
https://www.jiosaavn.com/album/hoova-chellona-banni-subrayanige/YR4F3a,MlR8_
https://www.jiosaavn.com/album/horaaada-mathe-nityanna-daathe/BuAww2ChTq8_
https://www.jiosaavn.com/album/hudagi-vara-bangaara-sara/6zJfWkM-rbE_
https://www.jiosaavn.com/album/hyanga-balaki-madabekanna-vol-3/8A-I2l2Xnlo_
https://www.jiosaavn.com/album/immortal-series-nadhaswara-samrat-sheik-chinna-moulana/iLb01zaVf0U_
https://www.jiosaavn.com/album/immortal-series-the-mellifluous-maharajapuram-santhanam/YPxqTl6g64k_
https://www.jiosaavn.com/album/indu-enage-govinda/Dd0ZOQKrN40_
https://www.jiosaavn.com/album/jagadodharaka-sai/-4NeuC-ZYfI_
https://www.jiosaavn.com/album/jaganmohanane-krishna/j3NO5xCsTbY_
https://www.jiosaavn.com/album/jana-hanumana-kandeera/pL4QzJBS3VE_
https://www.jiosaavn.com/album/jaya-jaya-kaliyugavarada/1-8v8ZCnkW4_
https://www.jiosaavn.com/album/jay-jay-mukunda-murari/HMmu5CpguGs_
https://www.jiosaavn.com/album/jay-jay-shri-trambakswar/TBSaBzPTggo_
https://www.jiosaavn.com/album/jeevana-sangaathi/ERoARmF55H0_
https://www.jiosaavn.com/album/jenumale-maadeva-male-madeshwara/jkB5iQGJuRU_
https://www.jiosaavn.com/album/kacchoora-maaldi-kadamallige-vol-2/cMPXVfyRDd4_
https://www.jiosaavn.com/album/kadugola-tarenna-chinnave./P026ogKCToQ_
https://www.jiosaavn.com/album/kaliyuga-kamadenu-sri-raghavendra/Xks8-ZMruCQ_
https://www.jiosaavn.com/album/kandu-dhanyanade/rOscKBIejPI_
https://www.jiosaavn.com/album/kannada-devotional-songs-vol-2/U5XC5K6vJoI_
https://www.jiosaavn.com/album/karunamoorthy-sri-mailara-linga/66SpCbhFNes_
https://www.jiosaavn.com/album/kateelda-devig-malligeda-parake/iW0keXRbb5g_
https://www.jiosaavn.com/album/kateelu-darshana/0Z0yEj0eNkg_
https://www.jiosaavn.com/album/kateelu-sri-durga-parameshwari-amruthavani/1651AVBo4Hk_
https://www.jiosaavn.com/album/katti-katti-irumudi-katti/yhIMs8GhkxM_
https://www.jiosaavn.com/album/kayabekenna-gopala/V9VrNltWdlo_
https://www.jiosaavn.com/album/kiladi-aliya/G1YWl9jWY-w_
https://www.jiosaavn.com/album/koti-chennaya/tVV5FZmv2T4_
https://www.jiosaavn.com/album/koti-chennaya-vol-1/fG1C-ExnYFc_
https://www.jiosaavn.com/album/kukkeya-vaasa-shri-surahmanya/oa2XClDr76A_
https://www.jiosaavn.com/album/kurukshethra-vol-1/vAZQnu36I6M_
https://www.jiosaavn.com/album/kurukshethra-vol-2/C0sjoSPSIGY_
https://www.jiosaavn.com/album/lava-kusha/DEipFQPhgKs_
https://www.jiosaavn.com/album/maddinadaaga-maja-north-karnataka-style-folk-songs/USxN,pq,ZLU_
https://www.jiosaavn.com/album/madhiimale-bhagya/bh,V0NwyOnA_
https://www.jiosaavn.com/album/madhimale-dareda-seere/bkaDMOd8jio_
https://www.jiosaavn.com/album/madhva-sampradaya-sandhya-vandane/0dhJph4umVE_
https://www.jiosaavn.com/album/mahamangalararathi/P66rVp7iVqg_
https://www.jiosaavn.com/album/mahamantra-gayatri/XbQTcyP1ZIw_
https://www.jiosaavn.com/album/maidala-rama/EcTXSdhDm5g_
https://www.jiosaavn.com/album/makkala-hadugalu/yH3QumoF2kI_
https://www.jiosaavn.com/album/malenada-mandakini/gSQfySKsQJA_
https://www.jiosaavn.com/album/maleyodeya-maadeshwara/M708UOdP55M_
https://www.jiosaavn.com/album/mallige-hoovinaage-maadeva/i7bZxMZJA6U_
https://www.jiosaavn.com/album/mamuna-magal/V3zXHoKCjGI_
https://www.jiosaavn.com/album/manteswamy-siddappaji-rochappaji/tyfHL0rCkmA_
https://www.jiosaavn.com/album/manthrakshatheya-needayya/9LbIjduOdPM_
https://www.jiosaavn.com/album/meghavarshini/C8CrnjeFuaw_
https://www.jiosaavn.com/album/mutthu-kollo-baale/OnnbN91fEf8_
https://www.jiosaavn.com/album/naadaswara/GnQY2bsUpyQ_
https://www.jiosaavn.com/album/nada-harshini-sxophone/9LYAl-3yXG0_
https://www.jiosaavn.com/album/nagashree-part-1/xa05ERVXC,M_
https://www.jiosaavn.com/album/nagashree-part-2/vqpEBXb8xWQ_
https://www.jiosaavn.com/album/nala-damayanthi./tH8f0qXxjb8_
https://www.jiosaavn.com/album/nala-damayanthi./Z0RBPfu9Z28_
https://www.jiosaavn.com/album/namo-oora-devta/IP0BjbiDIL4_
https://www.jiosaavn.com/album/namo-srinivasa/dix7R-Z205I_
https://www.jiosaavn.com/album/namo-vighna-raaja/w1UmupiQy7c_
https://www.jiosaavn.com/album/nanjanagudige-banniro/TREUYB7kqQ0_
https://www.jiosaavn.com/album/nanjanunda-nanjunda/gaDnxH2apMY_
https://www.jiosaavn.com/album/nanna-hendthi/N4ZNdnW5RPo_
https://www.jiosaavn.com/album/navaraatriya-devi-shri-kateelu-durg/ThZtg0KPd4Y_
https://www.jiosaavn.com/album/neeli-neeli-kanniwali/vN6jqcRFQRE_
https://www.jiosaavn.com/album/ningarajammana-kathe/AeBb,1wRPX8_
https://www.jiosaavn.com/album/omkareshwari-sri-chamundeshwari/ee49wj2yEx8_
https://www.jiosaavn.com/album/om-om-sri-ayyappa/nwqJU0-VSKk_
https://www.jiosaavn.com/album/ondu-kodthana-ondu-bidthana/d6s7EntjrMM_
https://www.jiosaavn.com/album/paavana-mooruthi-sri-sairam---jai-santhoshi-maatha/lTjx2D8n-BM_
https://www.jiosaavn.com/album/pandhari-shri-pandurang-vitthal/vxc,N2ib2qs_
https://www.jiosaavn.com/album/pedda-gedda/2O,wNWbpa6Q_
https://www.jiosaavn.com/album/pollag-pokala/wZ,qF7a-y6Q_
https://www.jiosaavn.com/album/purandaradasar-krithis/q2W3Gmp3Sj4_
https://www.jiosaavn.com/album/raaya-baaro-raghavendra-baaro-part-3/4MC1fq8wuVg_
https://www.jiosaavn.com/album/raghavendra-lakshmi-narasimha/lNxhn9M7CFk_
https://www.jiosaavn.com/album/ramana-bante-hanumantha/SYt-oI,buVI_
https://www.jiosaavn.com/album/sandhya-vandane-udupi-astamatha-sampradaya/ZjYLzzu3Yes_
https://www.jiosaavn.com/album/santha-gnaneshawara/UrfSSEJTL3M_
https://www.jiosaavn.com/album/savadatti-sri-ellamma-rakshamantra/IYDfA2CCgKE_
https://www.jiosaavn.com/album/saxophone-udupi-janardhan/BQICMsZDJ-w_
https://www.jiosaavn.com/album/shabari-bettakke-hogona/ChnECGtsoeY_
https://www.jiosaavn.com/album/shabarimale-swamy-ayyappa/d8DhXb51NHk_
https://www.jiosaavn.com/album/shambhoshankara-parameshwara/nLhANamPchk_
https://www.jiosaavn.com/album/sharade-shri-sharade/pKJX1q9R8bg_
https://www.jiosaavn.com/album/sharanu-shabareesha/WmnU0yu1WD8_
https://www.jiosaavn.com/album/sharanu-sharanu-chamundeshwari/80Q1VCBr7Lg_
https://www.jiosaavn.com/album/shiva-sthuthi/RON4O,ln4iM_
https://www.jiosaavn.com/album/shiva-stuthi-om-namah-shivaya/xwtfRJKJ-XU_
https://www.jiosaavn.com/album/shree-ram-raghuram/F79qfp0KKKk_
https://www.jiosaavn.com/album/shree-sai-amrutdhar/LqTtuRYrhn8_
https://www.jiosaavn.com/album/shri-anantapadmanabha-vratha/PjgYG0FEkZs_
https://www.jiosaavn.com/album/shri-durga-nava-ratnamala/jZHT8ruw2hs_
https://www.jiosaavn.com/album/shri-huligemma-devi/FJ6Ipzrjxc0_
https://www.jiosaavn.com/album/shri-huligemma-upasane-vol-1/63LHh2arSI8_
https://www.jiosaavn.com/album/shri-krishna-amrithvani/zgBQRRQ1Ekk_
https://www.jiosaavn.com/album/shri-maathaannapoorne-vandane/CJw,Xh9hdow_
https://www.jiosaavn.com/album/shukravaara-pooje/78EfXWQdlxE_
https://www.jiosaavn.com/album/sowbhagye-mahamaye/H1JwzOXSp6o_
https://www.jiosaavn.com/album/sravana-mangala-gowri-vratha/RwW54609Vjk_
https://www.jiosaavn.com/album/sri-adi-chunchanagiri-kshethramahat/Fm3A1pCZEmU_
https://www.jiosaavn.com/album/sri-ganesha-namana/CctMteCr2zc_
https://www.jiosaavn.com/album/sri-ganesha-suprabhatha/ehbTPXriQjQ_
https://www.jiosaavn.com/album/sri-goravanahalli-mahalakshig...../V5X12nb5aKo_
https://www.jiosaavn.com/album/sri-guru-bhajane/FRUjJ4WPFsY_
https://www.jiosaavn.com/album/sri-harivasa/rs4Gz-KjIg8_
https://www.jiosaavn.com/album/sri-huligemma-amrithwani/vyC9umEmANw_
https://www.jiosaavn.com/album/sri-kukke-subrahmanyeswara/5AIIcoSSH70_
https://www.jiosaavn.com/album/sri-mahalakshmi-pooja-vidhana/ULTCQ4WQ,,E_
https://www.jiosaavn.com/album/sri-mangaladevi/t6Z,L8T0pTA_
https://www.jiosaavn.com/album/sri-nanjundeswara/9n0Mu22IJqY_
https://www.jiosaavn.com/album/sri-sai-namaamruta/MCHVDuA6AUk_
https://www.jiosaavn.com/album/sri-shirdi-saibaba-amruthavani/sCxmWGMOba4_
https://www.jiosaavn.com/album/sri-venkatachala-nilayam/B62I5ipde5o_
https://www.jiosaavn.com/album/sri-venkateshwara-upasane/3HBGhRBMQTE_
https://www.jiosaavn.com/album/sshh-%21-kallara-rajya/Vw2L,nbWyrk_
https://www.jiosaavn.com/album/sundara-hudugi-thuppada-gadigi/Fp8kPeMDKM8_
https://www.jiosaavn.com/album/super-aliya/Y,fJBTHoT98_
https://www.jiosaavn.com/album/suprasanna-needu-ganapa/EMSd0xz-dLQ_
https://www.jiosaavn.com/album/swadara-maava/tyjNzjk0dw8_
https://www.jiosaavn.com/album/teenagers-hits-of-2004/d1z1LrgAwEo_
https://www.jiosaavn.com/album/thamma-hogona-arikeri-guddakke/mZVB7bWyXFM_
https://www.jiosaavn.com/album/thavaru/upxFUN4lPn8_
https://www.jiosaavn.com/album/thayulla-thavaru/INPaaivo41Y_
https://www.jiosaavn.com/album/thelikeda-barsolu-part-1/ihBdYAG9Nhs_
https://www.jiosaavn.com/album/thelikeda-barsolu-part-2/2fnG4Q-a51g_
https://www.jiosaavn.com/album/udri-maduve/,lpQhqQJzg0_
https://www.jiosaavn.com/album/udupi-sri-krishna-upasane/HBU,z6pwkE8_
https://www.jiosaavn.com/album/ughe-enni-madappange/G--g1DElefI_
https://www.jiosaavn.com/album/ullalthi-karnika/pA,FzCfe6IQ_
https://www.jiosaavn.com/album/uyyale-bannaduyyale/3WRWtRKdR7U_
https://www.jiosaavn.com/album/vandisuve-shree-mookambike/krcAWMEbU6s_
https://www.jiosaavn.com/album/veena-carnatic-classical/L3hBOJzbxUo_
https://www.jiosaavn.com/album/venkateshwara-raganjali/XeaCZVtm9ug_
https://www.jiosaavn.com/album/vitthal-vitthal-vithal-pandurang-vithal/EzoE95kVwhI_
https://www.jiosaavn.com/album/wah..re..wah...%21/o3KSwiaePgw_
https://www.jiosaavn.com/album/world-music-day---gems-of-carnatic-music/h6lt-QH5sR4_
https://www.jiosaavn.com/album/yankanchi-sri-davala-malika-amruthavani/ddtSM0AlIPg_
https://www.jiosaavn.com/album/yarado-duddu-yallammana-jatremuni/gZBmYKxwthg_
https://www.jiosaavn.com/album/yaru-nanna-ganda-comedy-drama/6qfysglhmOs_
https://www.jiosaavn.com/album/yedeyuru-sh.siddalingeshwara-mahatm/8FEnTTA24Yw_
https://www.jiosaavn.com/album/yedullu-manjunatha/lVTkvl4SfjU_

**Comment by chaitrakiran2010** [comment]
Thanks for your concern.... and Thanks once again for creating such a wonderful Tool for downloading Albums from JIOSaavn.

**Comment by bunnykek** [comment]
I have rewritten the code. Now it can fetch from all of your links.

**Comment by chaitrakiran2010** [comment]
Now it is working perfectly.....Thank you my friend... Thanks a lot....
